Fix added missing quote to openvox setup docs
Tiny fix that adds missing quote.
This prevents the following error:

```
root@puppet-client:~# puppet agent -t -v
Info: Using environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Notice: Requesting catalog from puppet-server:8140 (192.168.122.16)
Notice: Catalog compiled by puppet-server
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not parse for environment production: Syntax error at 'node' (file: /etc/puppetlabs/code/environments/production/manifests/site.pp, line: 17, column: 21) on node puppet-client
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Signed-off-by: Tom Bojer <t.bojer@shopware.com>